"""Add toppings and comment to order_items

Revision ID: c23a68a7ca00
Revises: 
Create Date: 2025-09-25 19:23:49.115846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c23a68a7ca00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('toppings', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('comment', sa.String(length=255), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.TEXT(),
               type_=sa.String(length=13),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_orders_customer'), ['customer'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_date'))
        batch_op.drop_index(batch_op.f('ix_orders_customer'))
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=13),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('comment')
        batch_op.drop_column('toppings')

    op.create_table('order',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('address', sa.VARCHAR(length=200), nullable=True),
    sa.Column('delivery_option', sa.VARCHAR(length=10), nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=20), nullable=False),
    sa.Column('items', sa.TEXT(), nullable=False),
    sa.Column('total', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
